### ISSUE TITLE
% drop from peak (when applicable)

### ISSUE THREAD

**Issue by SurajGupta** [eduardosasso/bullish#2]
Can you add the % change from the peak (all-time high)?  This is particularly useful in bear markets and during a recovery.

**Comment by eduardosasso** [comment]
Yeah that’s planned. I’ve been thinking about adding that to a weekend edition.

**Comment by eduardosasso** [comment]
Hi there, didn't forget about you. Took your suggestion and implemented it in a premium edition of the newsletter. See attached. Thanks for the feedback.

<img width="771" alt="Screen Shot 2020-07-08 at 4 44 50 PM" src="https://user-images.githubusercontent.com/65739/86981071-6f6e8780-c13a-11ea-88c2-55e913a46893.png">
