### ISSUE TITLE
CORS error in sugnup

### ISSUE THREAD

**Issue by ygalbel** [eduardosasso/bullish#4]
I tried to signup today, and got this errors:

![image](https://user-images.githubusercontent.com/4958307/79434364-f1855f00-7fd6-11ea-8f24-5f34e0a28ef6.png)

**Comment by eduardosasso** [comment]
Apologies. Send me your email in a DM and I can add you manually until I fix this issue.

**Comment by ygalbel** [comment]
My mail is ygalbel@gmail.com.
Thanks

**Comment by eduardosasso** [comment]
Done.
